#!/bin/bash
################################################################################
# Copyright (c) 2021 ModalAI, Inc. All rights reserved.
#
# author: james@modalai.com
################################################################################


# don't error out, if something goes wrong we will exit explicitly with exit 1
set +e

MIN_VERSION="3.3.0"
VERSION_FILE="/etc/version"
PACKAGE_NAME="voxl-tflite-server"

continue_or_quit () {
	echo "would you like to continue or quit?"
	select opt in "continue" "quit"; do
	case $opt in
		continue )
			break;;
		quit )
			exit 1
			break;;
		*)
			echo "invalid option"
			esac
	done
}

## each separate version number must be less than 3 digit wide !
function version {
	echo "$@" | awk -F. '{ printf("%03d%03d%03d\n", $1,$2,$3); }';
}


# make sure version file exists
if [ -f ${VERSION_FILE} ]; then
	V_STRING=$(cat ${VERSION_FILE})
else
	echo "Error, can't find file ${VERSION_FILE}"
	continue_or_quit
	exit 0
fi

# fetch last word from the version string
CURRENT_VERSION=${V_STRING##* }

## print what's going on
echo "${PACKAGE_NAME} installer detected system image ${CURRENT_VERSION}"


if [ "$(version "${CURRENT_VERSION}")" -ge "$(version "${MIN_VERSION}")" ]; then
	exit 0
else
	echo ""
	echo "ERROR, this version of ${PACKAGE_NAME} requires system image>=${MIN_VERSION}"
	echo "if you know what you are doing, you can continue the install anyway"
	continue_or_quit
fi
